### ISSUE TITLE
Sponsorship alignment

### ISSUE THREAD

**Issue by libuk** [Afrotech-Fest/afrotech-fest.github.io#14]
I think maybe these could be centered? There's a quite a bit of white space on the right.

![screen shot 2017-09-20 at 21 24 58](https://user-images.githubusercontent.com/6377078/30666486-63b403ca-9e4c-11e7-9a21-ceca57bf1ea1.png)

**Comment by DebsDee** [comment]
Hey Dan,

Do you think we can resize the logos so they're more uniform and same-sized? Like so:
<img width="1085" alt="screen shot 2017-09-21 at 13 35 18" src="https://user-images.githubusercontent.com/7225720/30695917-d0d47950-9ed1-11e7-9359-0f077195c18a.png">

**Comment by libuk** [comment]
Sure, I'll look at these when I'm back home tonight.

**Comment by libuk** [comment]
@DebsDee There's only so much we can do to get these looking more uniform as Owl carousel is already setting an explicit width for all items. The problem here is that they all have different aspect ratios, so we'd have to edit them in photo editing software to get them all to align and then export them again.

Failing that, we could vertically centre them to get them all aligned at least. I'm thinking as well, do they need to be in a carousel? We could use `flexbox` to align them and having them out of a carousel ensures that all sponsors will be visible at all times (I assume most people won't scroll through the carousel).

Let me know your thoughts.

**Comment by DebsDee** [comment]
Hey Dan, I think the amendments we've made to the sponsorship page will do. Thanks for taking the time to look into this.
