### ISSUE TITLE
Investigate bundling options

### ISSUE THREAD

**Issue by libuk** [Afrotech-Fest/afrotech-fest.github.io#21]
Currently one of the main performance issues is due to render blocking stylesheets (10 in all), so compiling all of this css into one file would be ideal. In order to do this, we'd need to include a task runner like Gulp or use `npm` scripts to concatenate files.

**Comment by DebsDee** [comment]
Would either of these options conflict with Netlify's build option?

**Comment by libuk** [comment]
No, it should be fine. It'd be a build step that Netlify will run, just as it's running the `hugo` command.

**Comment by libuk** [comment]
- [x] Add gulp js
- [x] Convert `.css` files to `.scss` to enable fie concatenation
- [ ] Remove extra stylesheet calls in `head.html` and add to local `static-src` folder for bundling
- [ ] Minify CSS
- [ ] Configure Netlify to add `npm`/`gulp` steps to the build process
- [ ] Update `README.md` with instructions

The goal here is to get those 10 calls to stylesheets down to 1. I've started by converting `.css` files that used to live in `static/css/` to `.scss` and moved to a separate folder (`static-src/`). (No code has been changed, and you can continue to write regular css).

Gulp then concatenates the files into one `main.css`. There are still more stylesheets being linked in the `head` of the site (bootstrap, google fonts etc) which I'll add locally for it to also be bundled in `main.css`.
