### ISSUE TITLE
Extend festival schedule

### ISSUE THREAD

**Issue by DebsDee** [Afrotech-Fest/afrotech-fest.github.io#25]
Festival schedule needs to be extended to accommodate the quantity of information that's to be uploaded. Features needed:

- Tabs for each festival day
<img width="1285" alt="screen shot 2018-01-04 at 21 11 31" src="https://user-images.githubusercontent.com/7225720/34605817-e32fb980-f204-11e7-9847-644849880b29.png">

- Links in the schedule that trigger a pop-up with more information 
<img width="1124" alt="screen shot 2018-01-04 at 21 29 57" src="https://user-images.githubusercontent.com/7225720/34605850-0888262c-f205-11e7-9a06-30a2967bdfd5.png">
<img width="779" alt="screen shot 2018-01-04 at 21 37 49" src="https://user-images.githubusercontent.com/7225720/34605879-23f633b8-f205-11e7-8466-8874063a3d8f.png">

The pop-up used on the participants main page can be re-purposed for this.

I've created a new branch 'schedule' for this.

**Comment by DebsDee** [comment]
Hey @simlrh, thanks for helping with this! @libuk is going to work on the tabs and I thought you could help with the pop-up function.

**Comment by DebsDee** [comment]
We're after this functionality: https://githubuniverse.com/program/

**Comment by simlrh** [comment]
Ok, will look into this Saturday or Sunday, will cap at 1 day but no way it will take that long.

**Comment by DebsDee** [comment]
Hi @simlrh Thanks for the pop-up. I was wondering if we could use the styles (transitions and appearance) used here: http://www.afrotechfest.co.uk/participants/

Also, I'm getting this weirdness:

<img width="1042" alt="screen shot 2018-01-07 at 19 00 33" src="https://user-images.githubusercontent.com/7225720/34652957-15cbe83a-f3dd-11e7-9e9c-99f5332de408.png">

**Comment by DebsDee** [comment]
@simlrh I worked out the weirdness with the Head tag. I'll look into applying the styles myself too. Thanks!

**Comment by simlrh** [comment]
@DebsDee Yeah, those were unresolved merge conflicts, glad you caught it. Just make sure the `data-programme-modal-description` etc attributes are applied on the updated schedule style.

**Comment by DebsDee** [comment]
@simlrh sorry, being slow, this all works great! Thank you.

**Comment by DebsDee** [comment]
@simlrh Okay, so looks like the overlay's 'broken'. Not appearing on the participants page either.

**Comment by DebsDee** [comment]
Okay, seems modal-overlay was renamed speakers__modal-overlay

**Comment by simlrh** [comment]
I can have a quick look at the develop branch tomorrow, sounds like some changes overwritten in the merge. The description was in both but marked display:none in the normal view.

**Comment by DebsDee** [comment]
@simlrh Sure, tomorrow's fine. Noticed also that where two rows are side by side only the first one opens on click.

<img width="1152" alt="screen shot 2018-01-07 at 20 09 56" src="https://user-images.githubusercontent.com/7225720/34653652-e7533d82-f3e6-11e7-9c2e-a055edb54b4c.png">

**Comment by DebsDee** [comment]
@simlrh Think I sorted this by placing the data-programme-button on the programme-event class.
