### ISSUE TITLE
Fix empty div issues

### ISSUE THREAD

**Issue by DebsDee** [Afrotech-Fest/afrotech-fest.github.io#6]
Two empty divs being generated by the template. Not sure what's creating them.
<img width="1094" alt="screen shot 2017-09-02 at 12 57 49" src="https://user-images.githubusercontent.com/7225720/29995316-6642c7d8-8fde-11e7-8993-8e54d97210bb.png">

**Comment by DebsDee** [comment]
Fixed extra divs by removing footer.html partial from index.html

**Comment by DebsDee** [comment]
Turns out this wasn't fixed but hidden.

**Comment by DebsDee** [comment]
Not sure but think this is being created by the template loop. I'll tried to fix it but no dice.
<img width="931" alt="template-loop" src="https://user-images.githubusercontent.com/7225720/30343808-ae87875c-97f6-11e7-9f9c-f43de3c777eb.png">

**Comment by libuk** [comment]
Fixed in https://github.com/Afrotech-Fest/afrotech-fest.github.io/pull/9
