### ISSUE TITLE
Owl carousel

### ISSUE THREAD

**Issue by DebsDee** [Afrotech-Fest/afrotech-fest.github.io#7]
Display carousel on mobile only.

**Comment by DebsDee** [comment]
Right now the carousel is visible regardless of viewport. It'd be great if the items wrapped on desktop and were carousels on smaller screen sizes.

<img width="1375" alt="owl-items" src="https://user-images.githubusercontent.com/7225720/30343706-646fb5c2-97f6-11e7-9aa3-d8951ac8535c.png">

**Comment by libuk** [comment]
I've had a look at this and it'll require a refactor of the `sliders()` function in `front.js`. Will pick it up tonight.

**Comment by libuk** [comment]
Fixed in pull request: https://github.com/Afrotech-Fest/afrotech-fest.github.io/pull/12
